### ISSUE TITLE
Test Scenario: WebHook Updates

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#100]
When a webhook (resource group) is known and configured API side, and an update comes through, the plugin should:

- parse the incoming update;
- update any locally known resources with the updated information;
- ensure this only happens when updates are enabled; and
- ensure this only happens when the plugin is not in stand-alone mode.

**Comment by jkva** [comment]
Note: this currently only works when "pretty" permalinks are enabled. Perhaps the plugin should try to determine this and display a warning message if it's not the case.

**Comment by jkva** [comment]
Regarding the webhook updates not coming through while running docker, there are two options:

1) use https://ngrok.com/ (free account) to have a host that can be resolved to the wordpress docker container
2) run your wordpress docker instance on a remote VPS that can be reached via IP or hostname

**Comment by Pen-a11y** [comment]
Each of the webhook scenarios have been tested, and all of them work appropriately.

The next step for this scenario is to add a warning underneath the "Enable Coyote remote description updates" checkbox. The warning will tell the user when their WordPress is not using "pretty" permalinks, and that information can not be updated from coyote if their site is not using "pretty" permalinks.

**Comment by Pen-a11y** [comment]
The final step of the scenario has been finished. The warning underneath the "Enable Coyote remote description updates" checkbox has been implemented telling the user when their WordPress is not using "pretty" permalinks.
