### ISSUE TITLE
Test Scenario: Media Library Integration

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#103]
When the media library is used, the plugin should:

- integrate with its image details display, similar to #98;
- hook into the media manager's async (ajax) fetching of image information; and
- keep into account any plugin settings (profile, updates being enabled, standalone mode, et cetera.)
- ensure only images are processed (no PDFs, videos, etc)

**Comment by Pen-a11y** [comment]
Testing the Media Library, we can see that the following scenarios work correctly.
- While the coyote plugin is enables, the image details display works similar to https://github.com/coyote-team/coyote-wp/issues/98;
- hook into the media manager's async (ajax) fetching of image information; and 
- keep into account any plugin settings (profile, updates being enabled, standalone mode, et cetera.)
- ensure only images are processed (no PDFs, videos, etc)
