### ISSUE TITLE
Invalid Profile Alert appears when valid profile found

### ISSUE THREAD

**Issue by Pen-a11y** [coyote-team/coyote-wp#110]
In some instances when a valid profile is found both the valid profile and invalid profile alerts appear on the screen.

**Comment by Pen-a11y** [comment]
It looks like when the endpoint is changed to point to another coyote instance it first fails to retrieve the profile, which leads to the profile being null and creating the INVALID_PROFILE transient. 

The error given is:
` GetProfileRequest.ERROR: Error fetching profile: Invalid Coyote API response for http://192.168.1.130:3000//api/v1/profile/, status 401 {"class":"Coyote\\Request\\GetProfileRequest"} []`

**Comment by robbinrietdijk** [comment]
These alerts are deprecated with the latest refactors to Twig. @jkva is this still relevant or can this issue be closed?
