### ISSUE TITLE
Classify API endpoint configuration as advanced setting

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#113]

**Comment by jkva** [comment]
Currently included as task within #94.

**Comment by jkva** [comment]
Per conversation with @robbinrietdijk, the item "Metum" will also be moved to advanced settings.

**Comment by robbinrietdijk** [comment]
@jkva I can't move the API endpoint to the new "advanced settings" subpage because then a user can only change the value when the API key is linked to a profile. Or does a user always exists on https://staging.coyote.pics?

**Comment by robbinrietdijk** [comment]
Per conversation with @jkva "Make the advanced page always available (with only the endpoint URL when no profile is linked)"

**Comment by robbinrietdijk** [comment]
Pushed the changes to the linked branch. PR for issue-94 needs to be merged first before this PR can be created (this branch extends on the work from issue-94).

**Comment by jkva** [comment]
Closing as addressed by #122.
