### ISSUE TITLE
Replace is_admin() with current_user_can('administrator')

### ISSUE THREAD

**Issue by robbinrietdijk** [coyote-team/coyote-wp#121]
In the PluginConfiguration class the function userIsAdmin() suggests a check for the current user having an admin role in WordPress. The WordPress function is_admin() doesn't check a users role, this function returns true for admin pages.

"Determines whether the current request is for an administrative interface page. Does not check if the user is an administrator; use [current_user_can()](https://developer.wordpress.org/reference/functions/current_user_can/) for checking roles and capabilities."

See https://developer.wordpress.org/reference/functions/is_admin/

**Comment by jkva** [comment]
Ah, yeah. Good spot. I remember using `current_user_can` in another project for that same reason. I do recall finding it a bit vague in which capabilities one needs to evaluate. If you have suggestions, please add them to this issue 👍

**Comment by robbinrietdijk** [comment]
Renamed the issue and assigned myself to it

**Comment by jkva** [comment]
Closing as #123 was merged.
