### ISSUE TITLE
Move add_action('init', [$this, 'setupControllers']) in WordPressPlugin to setupPluginActionsAndFilters

### ISSUE THREAD

**Issue by robbinrietdijk** [coyote-team/coyote-wp#128]

**Comment by robbinrietdijk** [comment]
This was initially not in a WP hook, first was pugins_loaded for current_user_can check and later updated to init for i18n.

Check if these functions can be separated so the function can be restored to the original without a WP hook

**Comment by jkva** [comment]
Closed by #142.
