### ISSUE TITLE
Configure which post types to hook into

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#20]
Currently any post update is processed, and when one processes all existing posts on the configuration page, all posts with type of `post` and `page` are processed.

We might want to add a selection box or list of checkboxes (with sensible defaults) so users can configure this.

**Comment by sinabahram** [comment]
Does wp-chron help us here?

**Comment by jkva** [comment]
No, because I use a filter that fires when a post is updated. In this case it would be an extra check that says "is the type of the post that's being updated in our list of approved types".

**Comment by jkva** [comment]
Eventually the choice was made to default to posts, pages and media attachments.
