### ISSUE TITLE
Implement coyote callback handler

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#40]

**Comment by sinabahram** [comment]
Just noting that this got committed/deployed on the Coyote side, which you probably already know, @jkva.

**Comment by jkva** [comment]
@sinabahram the documentation for it, at least for its payload structure, doesn't seem part of the deployment. Is that correct?

**Comment by jkva** [comment]
Going by the code I seem to get a resource record. Cool, I can work with that.

**Comment by jkva** [comment]
https://github.com/coyote-team/coyote/commit/e6d2525bc593987eb91f568b3d943acccfa0de95#diff-fdc192dffcd6611e07e0edfa9cfb285eR13

**Comment by jkva** [comment]
Implemented via f569a38e04978f7b400b10f2b31966dff3054f7e
