### ISSUE TITLE
How to handle long-running deactivation process?

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#43]
In cases of installations where the plugin modified thousands of posts, restoring the original alt text can cause the plugin deactivation to time out.

It might make more sense to have the "restore original content" option be an explicit tool on the settings page, so it can work similarly to batch post processing and have its progress monitored.

**Comment by sinabahram** [comment]
+1 to this suggestion. Do the batch first, if requested, then deactivation is not dependent on this. Plus, this makes things more explicit anyways.

**Comment by jkva** [comment]
No longer relevant as per filter implementation.
