### ISSUE TITLE
Populate disabled alt text field on WordPress

### ISSUE THREAD

**Issue by NolanHill** [coyote-team/coyote-wp#76]
It could be helpful to have the disabled Alternative Text field in the [attachment details dialog](https://chsdmdev.wpengine.com/wp-admin/upload.php?item=38552) populated with the most recently approved alt description from Coyote. This would make it easy tell if it's necessary to go to Coyote to add a description.

**Comment by jkva** [comment]
Implemented via https://github.com/coyote-team/coyote-wp/commit/b1c16e0d511ce2af9baf555254f63dc11c497a1c
