### ISSUE TITLE
Deactivate Alt Text Field on Media Editor for Pages

### ISSUE THREAD

**Issue by NolanHill** [coyote-team/coyote-wp#80]
Just noticed that while the alt text field is disabled and linked to the respective coyote resource on _Posts_, the same is not true for the media editor on _Pages_ or _Events_. Apologies for not catching this sooner.

example: featured image selector on https://chsdmdev.wpengine.com/wp-admin/post.php?post=23465&action=edit, featured image selector on https://chsdmdev.wpengine.com/wp-admin/post.php?post=22281&action=edit

**Comment by jkva** [comment]
This was fixed in v1.5.
