### ISSUE TITLE
Host URIs appear to be incorrect

### ISSUE THREAD

**Issue by flipsasser** [coyote-team/coyote-wp#86]
I'm not clear on the origin of this issue but it would be great if you could track it down on your end while I check mine. Here's an example resource: https://staging.coyote.pics/organizations/60-cooper-hewitt-semipermanent/resources/416921

It appears that the host URI for that resource is just the source URI with the file extension cut off. I would argue that the root URL is at least one host URI that should be set for it, since it appears on the homepage: https://chsdmdev.wpengine.com/

Further, those host URIs are 404'ing out as they are apparently not valid.

Thanks for looking into it!

**Comment by jkva** [comment]
@flipsasser this was a bug in the way the parent posts were resolved. It's been addressed in v1.6, thank you 👍

**Comment by sinabahram** [comment]
@jkva  this is a pretty fundamental issue, so is there a way of retroactively fixing it for existing resources?

**Comment by jkva** [comment]
@sinabahram by running an import, yes. I've done so on CH's dev instance.

**Comment by sinabahram** [comment]
Sure, but how are we fixing in production. This is already running on prod.

**Comment by jkva** [comment]
@sinabahram I would expect it to be the same case; if an admin runs an import with the latest version of the plugin, any existing resources coyote-side will be amended with the correct host uri.

**Comment by sinabahram** [comment]
perfect
