### ISSUE TITLE
Alt text not grayed out in Exhibition post type

### ISSUE THREAD

**Issue by NolanHill** [coyote-team/coyote-wp#89]
cooperhewitt.org uses some custom post types, e.g. [Publication](https://chsdmdev.wpengine.com/wp-admin/post.php?post=39090&action=edit) and [Exhibition](https://chsdmdev.wpengine.com/wp-admin/post.php?post=37529&action=edit). I've noticed that in the media selector for these post types, the Alt Text field is not grayed out with a pointer to coyote. Not sure if it's possible to bring that feature to these post types, since they are custom to our site.

**Comment by jkva** [comment]
Hi Nolan. Yep, agreed. It seems we'd need a custom setting on the plugin page where one'd be able to toggle checkboxes to integrate with custom post types. I've filed #90 to cover this enhancement. cc @sinabahram

**Comment by robbinrietdijk** [comment]
Issue #90 is merged, this issue needs to be tested / confirmed if it's working in v2 or that this issue still exists.

**Comment by jkva** [comment]
This works well after further testing and addressing in #142.
