### ISSUE TITLE
Replace the regular-expression based DOM parsing with DOM Module

### ISSUE THREAD

**Issue by Pen-a11y** [coyote-team/coyote-wp#93]
Currently we are using regular-expression based DOM parsing. 

We would like to migrate over to using the [DOM Module](https://www.php.net/manual/en/book.dom.php) that is within PHP.

Previously there have been issues using this with WPEngine, but it seems that these problems have been resolved.

**Comment by jkva** [comment]
# ContentHelper spec

Initially the ContentHelper using the DOM Module does not need to be more than a list of functions. A set of unit tests will verify they behave as expected. When the functionality is as required, it can be integrated within the plugin.

## Functions:

### `get_images(string $html): DOMElement[]`

Given a html string, either an entire or partial document, return all image elements (these can be DOMElement instances)

### `get_image_caption(DOMElement $element): ?string`

Given a DOMElement node, return either null or its caption

### `get_image_alt(DOMElement $element): ?string`

Given a DOMElement node, return either null or its alt

### `get_image_attr_src(DOMElement $element): ?string`

Given a DOMElement node, return either null or its src attribute

### `get_image_attachment_src(DOMElement $element): ?string`

Given a DOMElement node, return either null or its attachment src
_this requires `coyote_attachment_url()`, also see if you still want to use something like the existing `get_class_attachment_id()`. It might be good to use a mocked `coyote_attachment_url()` function within the test._

### `set_image_alt(DOMElement $element, string $alt): DOMElement`

Given an image DOMElement node and a string, set its alt attribute value. Be careful of data sanitation.

### `set_image_alts(string $html, []<string => string>): string`

Given a html string, either an entire or partial document, and a map of image sources and their alt attributes, set the alt text for each image and return the modified html

## Test Scenarios:

* Get all images from well-formed HTML with some images
* Get all images from well-formed HTML without images
* Set the alt for an image
* Set unescaped alt for an image
* Get the alt for an image
* Get the alt for an image when there is no alt
* Get the src for an image
* Get the src for an image when there is no src
* Get the caption for an image (do you know how WordPress formats those? Check the regex in the existing code)
* Get the caption for an image where there is none
* Get the class for an image
* Get the class for an image where there is none
* Get the attachment src where there is a valid attachment class with id
* Get the attachment src where there is no valid attachment class id
* Get the attachment src when there is no class at all
* Set the image alts with a valid map of `src => alt` pairs
* Set the image alts with an empty map
* Set the image alts for html without images
* Set the image alts for badly formed html
* Set the image alt for an image with a specific `src`
* Set the image alt for images that exist multiple times

Are there more scenarios you can think of?

**Comment by Pen-a11y** [comment]
So far I have not been able to think of other scenarios to test for. At the moment I have finished many of the functions, and I am in the process of getting the PHPUnit tester to work appropriately. 

One question I had was what would the caption of the image be? Is this talking about a `<figcaption>` tag within a `<figure>`?

Also should there be more functions included within the ContentHelper? As some of these scenarios that are given seem like they would need to be in separate functions then the ones provided above

**Comment by Pen-a11y** [comment]
@jkva I looked into the issue we discussed yesterday of HTML5 not being loaded appropriately with PHP DOM Module, and it was correct. 

I was checking to see if there were any alternatives and it looks like the best option is [HTML5-PHP](https://github.com/Masterminds/html5-php)

It still lets us load it into a DOM Document, I'd love to hear your input on it as well.

**Comment by jkva** [comment]
Closing as currently implemented in V2 via the `ContentHelper` package.
