### ISSUE TITLE
Improve Rendering and Functionality of Settings Page

### ISSUE THREAD

**Issue by Pen-a11y** [coyote-team/coyote-wp#94]
The way that WordPress traditionally handles a settings page could lead to code that is messy, and hard to read. 

To improve the functionality of the Settings Page we need to create a configuration model layer, that uses Twig templates and JavaScript to improve the rendering and functionality of the pages.

**Comment by jkva** [comment]
This supersedes #21.

Effectively:

* Split up Coyote Settings into its own sidebar menu, with the sub-items "Settings" and "Tools"
* Use Twig (or another time-proven PHP templating engine) for view rendering
* Optionally generate a _ViewModel_ which feeds into the settings view, perhaps also tools
* Move the setting "API endpoint" into advanced settings, defaulting to the live endpoint

**Comment by jkva** [comment]
The templating engine item has been split to #117.

**Comment by jkva** [comment]
The "API endpoint to advanced settings" item will remain a separate issue as #113.

**Comment by robbinrietdijk** [comment]
In first review with @jkva decided to refactor array arguments in actions and filters to braces "[]" instead of "array()". Will work this out before creating a Pull Request.

**Comment by jkva** [comment]
Closing as addressed via #118.
