### ISSUE TITLE
Test Scenario: Content Parsing

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#97]
The plugin should:

- attempt to replace the image description for any image within a post or page; and
- attempt to fetch image information from the Coyote API when the plugin does not know about the image locally, and the plugin is configured and not in stand-alone mode.

**Comment by Pen-a11y** [comment]
After testing these 2 scenarios we can see that the functionality isn't currently working for either scenario.

When image description is changed within the Coyote site it is not changed within posts
And at the moment the image information does not seem to be getting fetched correctly from the Coyote API when the plugin is configured

**Comment by jkva** [comment]
> When image description is changed within the Coyote site it is not changed within posts

This seems related to #100, correct?

> at the moment the image information does not seem to be getting fetched correctly from the Coyote API when the plugin is configured

Is the above still an issue at the time of this writing?

**Comment by jkva** [comment]
This has been discussed as resolved during the last check-in.
