### ISSUE TITLE
Test Scenario: Classic Editor Integration

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#98]
When using the Classic Editor, the plugin should:

- set alt-text fields to readonly;
- when the image is known to the plugin render a management link; and
- display the custom alt text that the plugin has for the image.

**Comment by Pen-a11y** [comment]
Going through the Classic Editor Integration scenarios, all of the scenarios are implemented to a certain degree

- set alt-text fields to readonly:
Is implemented fully as users can not edit the alt-text field
- when the image is known to the plugin render a management link:
Is implemented but not tested fully, the image management link does appear and when activated does go to the endpoint. At the moment I am unable to test it when I am a logged in user, so until then it will not be fully implemented.
- display the custom alt text that the plugin has for the image:
 Is implemented but not tested fully, after a test instance of Coyote is able to be created then we will know if it works fully as at the time we know that it will display what is currently the custom alt text, but have not seen if it will display newly edited text from the Coyote site.

**Comment by Pen-a11y** [comment]
After testing with a Docker contained Coyote as the endpoint I was able to test the functionality of these scenarios.

- when the image is known to the plugin render a management link:
This scenario is implemented fully, and when the user is sent to the Coyote endpoint they can edit and change the alt, caption and other parts of the image in the Coyote endpoint
- display the custom alt text that the plugin has for the image:
Currently this functionality is not implemented, and when the alt is changed in the Coyote endpoint the Alt Text doesn't change in the WordPress instance

**Comment by Pen-a11y** [comment]
After testing again with a configured endpoint using ngrok the scenarios that were not implemented fully work correctly, and all scenarios for this test case function as they are supposed to.
